language: python
addons:
  firefox: latest
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - xvfb
# command to run tests
script:
  - python3 manage.py test
after_success:
  - coveralls
